name: ChunkShield
version: '1.0-1.21.5'
main: me.sintaxlabs.chunkShield.main
api-version: '1.21'

commands:
  reloadconfig:
    description: Reloads the ChunkShield config
    usage: /chunkshield <subcommand>
    aliases: [ chunkshield, cshield ]
    permission: chunkshield.reload

permissions:
  chunkshield.reload:
    description: Allows user to reload the ChunkShield plugin.
    default: op