name: ChunkShield
version: '1.0.1'
main: me.sintaxlabs.chunkShield.main
api-version: '1.21'

commands:
  reloadconfig:
    description: Reloads the ChunkShield config
    usage: /chunkshield <subcommand>
    aliases: [ chunkshield, cshield ]
    permission: chunkshield.reload

permissions:
  chunkShield.reload:
    description: Allows user to reload the ChunkShield plugin.
    default: op
  chunkShield.verbose:
    description: Allows user to see messages confirming events.
    default: op